services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /instance:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - COREBOT_URL=http://172.25.141.186:8000
      - COREBOT_API_KEY=corebot-dev-key
      - APP_VERSION=todo-app-1.0.0
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
 #     start_period: 40s
    restart: Never
      #    profiles:
      #      - dev
      #      - prod

volumes:
  instance:

